### ISSUE TITLE
add support for LAUNCH_GROUP

### ISSUE THREAD

**Issue by bklaas** [osallou/python-mesos-http#7]
Currently the Offers.accept() method can only send a list of tasks to perform in parallel via the Mesos API via LAUNCH. The Mesos API also supports LAUNCH_GROUP, which allows for multi-stage task lists. That is, a stage 1 where tasks 1,2,3 are run in parallel, followed by a stage 2 where tasks 4,5,6 are run in parallel (but after all tasks in stage 1 are complete).

Are you considering adding this as a supported feature to python-mesos-http?

**Comment by osallou** [comment]
Hi,
I do not plan any new development for now.
I made this library a while ago to fit my needs, not to be fully compliant with mesos. However feel free to submit a PR

The pymesos library did not use at this time the http api, that was my issue. Now it does, maybe this lib is more in sync with mesos now..

**Comment by bklaas** [comment]
Thanks for the quick response. I've forked your repo and am seeing if I can get it working myself. Will submit PR if I do.
